runtime: nodejs20
instance_class: F1

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
